export VISUAL="$(command -v nvim || command -v vim || command -v nano || command -v vi)"
export EDITOR="$VISUAL"
export SUDO_EDITOR="$VISUAL"
export PAGER="$(command -v less || command -v more)"
export TERMINAL="$(command -v konsole || command -v gnome-terminal || command -v xfce4-terminal || command -v qterminal || command -v xterm)"
